version: '3.9'
services:

  
    mongodb:
      image : mongo:4.4
      environment:
      - PUID=1000
      - PGID=1000
      volumes:
      - ${PWD}/mongodb:/data/db
      ports:
      - 27017:27017
      restart: always
      command: --quiet --logpath /dev/null

    susteyn-backend:
      image: emilsallem/rowa-backend:feature-backendrewrite-latest
      ports:
        - 5000:5000
      restart: always
      environment:
        MONGODB_HOST: mongodb
      volumes:
        - ${PWD}/backend/data:/app/data
        - /etc/localtime:/etc/localtime:ro
      logging:
        driver: "local"
      privileged: true
      environment:
        MONGO_HOST: mongodb
        GPIOZERO_PIN_FACTORY: mock
      
    


volumes:
  mongodb: