version: '3.9'
services:

  
    mongodb:
      image : mongo
      container_name: mongodb
      environment:
      - PUID=1000
      - PGID=1000
      volumes:
      - ${PWD}/mongodb:/data/db
      ports:
      - 27017:27017
      restart: unless-stopped

    susteyn-backend:
      image: emilsallem/susteyn-backend:latest
      ports:
        - 3000:3000
      environment:
        - TZ="Europe/Berlin"
      
      logging:
        driver: "local"
      privileged: true

volumes:
  mongodb: