version: '3.8'
services:

  rowa-backend:
    image: emilsallem/rowa-backend:customer-expresssteuer-latest
    container_name: backend
    ports:
      - 3000:3000
    environment:
      - TZ="Europe/Berlin"
    volumes:
      #-  "/home/pi/Documents/rowa.db:/ROWA/rowa.db"
      - /dev:/dev
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "local"
    privileged: true
        
  
   
  rowa-frontend:
    image: emilsallem/rowa-frontend:dev-latest
    container_name: frontend
    ports:
      - 8080:80
    logging:
      driver: "local"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
      
    command: --interval 30 --debug
    
  telegraf:
    image: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      FARM_ID: ${FARM_ID}
      BUCKET: ${BUCKET}


    hostname: localhost
    volumes:
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
      
