version: '3.9'
services:

  
    mongodb:
      image : mongo
      container_name: mongodb
      environment:
      - PUID=1000
      - PGID=1000
      volumes:
      - ${PWD}/mongodb:/data/db
      ports:
      - 27017:27017
      restart: unless-stopped

    susteyn-backend:
      image: emilsallem/rowa-backend:feature-backendrewrite-latest
      ports:
        - 5000:5000
      environment:
        MONGODB_HOST: mongodb

      
      logging:
        driver: "local"
      privileged: true

volumes:
  mongodb: