version: '3.8'
services:

  rowa-backend:
    image: emilsallem/rowa-backend:master-latest
    container_name: backend
    ports:
      - 3000:3000
    environment:
      - TZ="Europe/Berlin"
    volumes:
      -  "/home/pi/Documents/rowa.db:/ROWA/rowa.db"
      -  "/dev:/dev"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    logging:
      driver: "local"
    privileged: true
        
  
   
  rowa-frontend:
    image: emilsallem/rowa-frontend:master-latest
    container_name: frontend
    ports:
      - 8080:80
    environment:
      - TZ="Europe/Berlin"
    logging:
      driver: "local"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      
    command: --interval 600 --debug
    
