version: '3.9'
services:

  
    mongodb:
      image : mongo
      container_name: mongodb
      environment:
      - PUID=1000
      - PGID=1000
      volumes:
      - ${PWD}/mongodb:/data/db
      ports:
      - 27017:27017
      restart: unless-stopped

    
    
    susteyn-frontend:
      image: emilsallem/rowa-frontend:feature-frontend2.0-latest
      container_name: frontend
      ports:
        - 8080:80
      environment:
        - TZ="Europe/Berlin"
      logging:
        driver: "local"

volumes:
  mongodb: