openapi: 3.0.0
servers: []
info:
  description: Standard Susteyn API for FarmV3.0
  version: 1.0.0
  title: Susteyn API for FarmV3.0
  contact:
    email: team@susteyn.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: planting
    description: Planting endpoints
  - name: harvesting
    description: Harvesting Endpoints
paths:
  /dashboard/farm/{moduleNumber}:
    get:
      tags:
        - planting
      summary: return plants in given module
      operationId: returns plants in module
     
      parameters:
        - in: path
          name: moduleNumber
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: module number valid
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/allPlantsInModule'
       
  /plant/finish:
    get:
      tags:
        - planting
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
     
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlantablePlants'
        '400':
          description: bad input parameter
          
          
    post:
      tags:
        - planting
      summary: adds an inventory item
      operationId: addInventory
      description: Adds an item to the system
      responses:
        '200':
          description: search results matching criteria
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModuleToPlant'
        description: Inventory item to add
  /dashboard/plantable-plants:
    get:
      tags:
        - planting
      summary: returns plantable plants
      operationId: getPlantablePlants
      description: |
        returns plantable plants
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlantablePlants'
        '400':
          description: bad input parameter
          
          
  /admin/toggle-light:
    get:
      tags:
        - light
      summary: triggers light
      operationId: toggleLight
      description: |
        triggers light
      responses:
        '200':
          description: search results matching criteria
        '404':
          description: not found
          
  /admin/toggle-pump:
    get:
      tags:
        - pump
      summary: triggers pump
      operationId: togglePump
      description: |
        triggers pump
      responses:
        '200':
          description: search results matching criteria
        '404':
          description: not found
          
  /admin/toggle-airstone:
    get:
      tags:
        - airstone
      summary: triggers airstone
      operationId: airstoneToggle
      description: |
        triggers airstone
      responses:
        '200':
          description: search results matching criteria
        '404':
          description: not found

          
  /admin/change-planttype:
    post:
      tags:
        - admin
      summary: returns plantable plants
      operationId: changePlanttype
      description: |
        returns plantable plants
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeModulePlants'
        '400':
          description: bad input parameter
  
components:
  schemas:
    allPlantsInModule:
      type: object
      required:
        - variety
        - plantDate
        - growthTime
        - plantPosition
      properties:
        variety:
          type: string
          example: Neckar Giant
        plantDate:
          type: string
          example: '01/01/2020'
        position:
          type: integer
          example: 3
        growthTime:
          type: integer
          example: 42
    PlantablePlants:
      type: object
      required:
        - plantType
        - module
        - plantableSpots
      properties:
        plantType:
          type: string
          example: Neckar Giant
        module:
          type: integer
          example: 2
        position:
          type: integer
          example: 3
    ModuleToPlant:
      type: object
      required:
        - modulenum
        - variety
      properties:
        modulenum:
          type: integer
          example: 1
        variety:
          type: string
          example: Neckar Giant
    ChangeModulePlants:
      type: object
      required:
        - modulenum
        - variety
      properties:
        modulenum:
          type: integer
          example: 1
        varieties:
          type: array
          items:
            type: string
            example: Mint
