name: Frontend build
'on':
  - workflow_dispatch
jobs:
  buildx:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: >-
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{
          secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image
        run: >-
          docker build --platform linux/amd64,linux/arm/v7 --output
          "type=image,push=true" --tag
          emilsallem/rowa-backend:videofront-$GITHUB_RUN_NUMBER ./backend/.      
      
